config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get 'home/index'
  
    
  resources :categories do
    resources :projects do
      resources :pics
    end
  end
  

   root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_attached_file :image_path, styles: { medium: "300x300>", thumb: "100x100>", large: "500x500" },default_url: "/images/:style/missing.png", :default_style => :medium

	has_many :projects

	validates_attachment :image_path, 
      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] },
      :size => { :in => 0..5000.kilobytes }

	validates :name, presence: true
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	has_attached_file :pic_path, styles: { medium: "300x300", thumb: "100x100>", large: "500x500" }, default_url: "/images/:style/missing.png", :default_style => :medium

	validates_attachment :pic_path, 
      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] },
      :size => { :in => 0..5000.kilobytes } 

    validates :title, presence: true


	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :main_image_path, styles: { medium: "300x300>", thumb: "100x100>", large: "500x500" },default_url: "/images/:style/missing.png", :default_style => :medium

	validates_attachment :main_image_path, 
      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] },
      :size => { :in => 0..5000.kilobytes } 

	validates :title, presence: true

	belongs_to :category
	has_many :pics
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def new
  	@category = Category.new()
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def create
  	@category = Category.new( category_params )
  	if @category.save
  		redirect_to root_path
  	else
  		render 'new'
  	end 
  end

  def update
  	@category = Category.find(params[:id])

  	if @category.update( category_params )
  		redirect_to category_path
  	else
  		render 'edit'
  	end
  end

  def show
  	@category = Category.find(params[:id])
  end

  def destroy
  	@category = Category.find(params[:id])
  	@category.destroy

  	redirect_to root_path
  end

  private
	
	def category_params
  		params.require(:category).permit(:image_path, :name, :description)
	end
  
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def new
		@pic = Pic.new()
	end

	def edit
		@pic = Pic.find(params[:id])
	end

	def create
		@pic = Pic.new( pic_params )
		if params[:showable] == "1"
			@pic.showable = true
		end
		@pic.project_id = params[:project_id]
		if @pic.save
			redirect_to category_project_pic_path(params[:category_id], params[:project_id], @pic)
		else
			render 'new'
		end
	end

	def update
		@pic = Pic.find(params[:id])
		if @pic.update( pic_params )
			redirect_to category_project_pic_path
		else
			render 'edit'
		end
	end

	def show
		@pic = Pic.find(params[:id])
		@project = Project.find(@pic.project_id)
	end

	def destroy
		@pic = Pic.find(params[:id])
		project = Project.find(params[:project_id])
		@pic.destroy

		redirect_to category_project_path(params[:category_id], params[:project_id])
	end

	private
	
	def pic_params
  		params.require(:pic).permit(:title, :description, :pic_path, :project_id, :showable)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
	end

	def new
		@project = Project.new()
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create 
		@project = Project.new( project_params )
		@project.category_id = params[:category_id]

		if @project.save
			redirect_to "/categories/#{@project.category_id}/projects/#{@project.id}"
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to "/categories/#{@project.category_id}/projects/#{@project.id}"
		else
			render 'edit'
		end
	end

	def show
		if params[:id]
			@project = Project.find(params[:id])
		else
			@project = Project.find(params[:project_id])
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to category_path(params[:category_id])
	end

	private
	
	def project_params
  		params.require(:project).permit(:main_image_path, :title, :sales_pitch, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_about.html.erb
<section class="container">
  <section class="row">
    <div class="col-sm-5 offset-2">
      <h1><%= category.name.upcase %></h1>
      <p class="lead description"><%= category.description %></p>
    </div>
    <div class="col-sm-5">
      <%= image_tag(category.image_path, alt: category.name, class: "img-fluid") %>
    </div>
  </section>
  <hr>
  <div class="col-sm-4 m-t-3">
    <%= render partial: "categories/contact" %>
  </div>
</section>

app/views/categories/_contact.html.erb
<h3>Contact:</h3>
<p class="lead">ayesha.agha@gmail.com</p>
<h3>Find me on social media:</h3>
<div class="social m-t-2">
  <%= link_to image_tag("linkedin.png", alt:"Linked In"), "https://www.linkedin.com/in/ayeshaagha", target:"_blank"  %>
</div>
<h3 class="m-t-2">Professional Resume:</h3>
<%= link_to image_tag("pdf.png", alt:"Resume PDF"), asset_path("Brett-Ripley.pdf"), target:"_blank" %>

app/views/categories/edit.html.erb
<section class="container text-sm-center">
  <%= form_for @category, url: category_path, html: { multipart: true }, method: :patch do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@category.errors.count, "error") %> prohibited
          this category from being saved:
        </h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :category_description%><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.file_field :image_path %>
    </p>
    <p>
      <%= form.submit "Update Category",class: "btn btn-primary" %>
    </p>
  <% end %>
</section>

app/views/categories/index.html.erb
<% categories = Category.all %>
<% if current_user %>
  <div class="container">
    <%= link_to "Add Project Category", new_category_path, class: "btn btn-primary" %>
  </div>
<% end %>
<section class="container m-t-3">
  <% categories.each do |category| %>
    <div class="col-sm-3 bw blur pic">
        <%= link_to image_tag(category.image_path.url(:medium),  alt: category.name, class: "img-fluid"), category %>
        <h3 class="category-title"><%= category.name.capitalize %></h3>
    </div>
  <% end %>
</section>

app/views/categories/new.html.erb
<section class="container text-sm-center">
  <%= form_for @category, url: categories_path, html: { multipart: true } do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@category.errors.count, "error") %> prohibited
          this category from being saved:
        </h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :category_description%><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.file_field :image_path %>
    </p>
    <p>
      <%= form.submit "Create Category",class: "btn btn-primary" %>
    </p>
  <% end %>
</section>

app/views/categories/show.html.erb
<%= render partial: "layouts/nav", locals: {category: @category}  %>
<% if current_user %>
  <div class="container">
    <%= link_to "Add #{@category.name.capitalize} Project", new_category_project_path(@category), class: "btn btn-primary" %>
    <%= link_to "Edit #{@category.name.capitalize}", edit_category_path, class: "btn btn-primary" %>
    <%= link_to "Delete #{@category.name.capitalize}", category_path,
      method: :delete,
      data: { confirm: 'Kill the fuck out of this project category, Ayesha?' },
      class: "btn btn-primary" %>
  </div>
<% end %>
<section class="container">
  <% if @category.name == 'about' %>
    <%= render partial: "categories/about", locals: {category: @category} %>
  <% else %>
    <div class="col-lg-6 col-lg-offset-3 m-b-3 m-t-3">
      <h1><%= @category.name.upcase %></h1>
      <p class="lead description"><%= @category.description %></p>
    </div>
</section>
<section class="container">
    <% @category.projects.each do |project| %>
      <div class="col-sm-3 m-b-2 blur bw pic">
        <%= link_to image_tag(project.main_image_path.url(:medium),  alt: project.title, class: "img-fluid"), category_project_path(@category.id, project) %>
        <h3 class="category-title"><%= project.title %></h3>
      </div>
    <% end %>
  <% end %>
</section>

app/views/category/index.html.erb
<% categories = Category.all %>
<section class="container">
  <% categories.each do |category| %>
    <div class="col-sm-3">
      <%= link_to image_tag("#{category.image_path}",  alt: category.name, class: "img-fluid"), "category#show" %>
    </div>
  <% end %>
</section>

app/views/layouts/_footer.html.erb
<section class="container footer">
  <div class="col-sm-3 social">
    <%= link_to image_tag("linkedin.png", alt:"Linked In"), "https://www.linkedin.com/in/ayeshaagha", target:"_blank"  %>
  </div>
  <div class="col-sm-3  col-sm-offset-2 text-center">
    <p class="lead">&copy;AYESHA AGHA</p>
  </div>
  <div class="col-sm-3 col-sm-offset-1">
    <p class="lead">ayesha.agha@gmail.com</p>
  </div>
</section>

app/views/layouts/_nav.html.erb
<% if category.name != "about" %>
  <nav class="navbar">
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#responsiveCollapse">
      ☰
    </button>
    <div class="collapse navbar-toggleable-xs" id="responsiveCollapse"> <!-- class .navbar-toggleable-* -->
      <ul class="nav navbar-nav">
          <% if params[:category_id] %>
            <% category = Category.find(params[:category_id]) %>
            <li class="nav-item">
              <%= link_to "Back to #{category.name}", category_path(category), class: "nav-link" %>
            </li>
          <% end %>
          <% if params[:project_id] %>
            <% category = Category.find(params[:category_id]) %>
            <% project = Project.find(params[:project_id]) %>
            <li class="nav-item">
            <%= link_to "#{project.title.capitalize}", category_project_path(category, project), class: "nav-link" %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
<% else %>
  <nav class="navbar bg-inverse">
      <%= link_to "AYESHA", root_path, class: "navbar-brand" %>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ayesha Agha</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="jumbotron">
    <%= link_to root_path, class: "logo" do %>
      <h1 class="display-1">AYESHA AGHA</h1>
      <hr>
    <% end %>
    <p class="lead" id="tagline">My site is better than Samuel S. Powers'</p>
    <ul class="nav">
      <%if current_user %>
        <li><h5>Hey Sexy</h5></li>
        <!-- <li class='nbtn'><a href="/users/show">My Profile</a></li> -->
        <li><%= link_to "Signout", destroy_user_session_path, method: :delete, class: "btn btn-primary" %></li>
      <%else%>

      <% end %>
    </ul>
    <% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% end %>
  </section>

  <%= yield %>

  <%= render partial: "layouts/footer" %>
</body>
</html>

app/views/pics/edit.html.erb
<section class="container text-sm-center">
  <h3>Edit This Image</h3>
  <%= form_for @pic, url: category_project_pic_path, html: { multipart: true }, method: :patch do |form| %>
    <% if @pic.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@pic.errors.count, "error") %> prohibited
          this image from being saved:
        </h2>
        <ul>
          <% @pic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= check_box_tag(:showable) %>
      <%= label_tag(:showable, "Give this image a show page?") %>
    </p>
    <%= form.file_field :pic_path %>
    <%= form.submit "Upload Image", class: "btn btn-primary" %>
  <% end %>
<section class="container text-sm-center">

app/views/pics/new.html.erb
<section class="container text-sm-center">
  <h3>Add Images To This Project</h3>
  <%= form_for @pic, url: category_project_pics_path, html: { multipart: true } do |form| %>
    <% if @pic.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@pic.errors.count, "error") %> prohibited
          this image from being saved:
        </h2>
        <ul>
          <% @pic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= check_box_tag(:showable) %>
      <%= label_tag(:showable, "Give this image a show page?") %>
    </p>
    <%= form.file_field :pic_path %><br>
    <%= form.submit "Upload Image", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/pics/show.html.erb
<%= render partial: "layouts/nav", locals: {category: Category.find(@project.category_id)}  %>
<section class="container">
  <% if current_user %>
    <%= link_to "Edit Image", edit_category_project_pic_path, class: "btn btn-primary" %>
    <%= link_to "Delete Image", category_project_pic_path,
      method: :delete,
      data: { confirm: 'Get rid of this image because it sucks, Ayesha?' },
      class: "btn btn-primary" %>
    <%= link_to "Back to Project", category_project_path(params[:category_id], params[:project_id]), class: "btn btn-primary" %>
  <% end %>
  <div class="col-sm-8 m-t-3">
    <%= image_tag(@pic.pic_path.url(:large), alt: @pic.title, class: "img-fluid") %>
    <h1 class="m-t-3"><%= @pic.title %></h1>
    <hr>
    <p class="lead"><%= @pic.description %></p>
  </div>
</section>

app/views/projects/edit.html.erb
<section class="container text-sm-center">
  <h1>Editing project</h1>

  <%= form_for @project, url: category_project_path, html: { multipart: true }, method: :patch do |form| %>

    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@project.errors.count, "error") %> prohibited
          this project from being saved:
        </h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :tag_line %><br>
      <%= form.text_field :sales_pitch %>
    </p>
    <p>
      <%= form.label :project_description%><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.file_field :main_image_path %>
    </p>

    <p>
      <%= form.submit "Edit Project",class: "btn btn-primary" %>
    </p>

  <% end %>
</section>

app/views/projects/new.html.erb
<section class="container text-sm-center">
  <%= form_for @project, url: category_projects_path, html: { multipart: true } do |form| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@project.errors.count, "error") %> prohibited
          this project from being saved:
        </h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :tag_line %><br>
      <%= form.text_field :sales_pitch %>
    </p>
    <p>
      <%= form.label :project_description%><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.file_field :main_image_path %>
    </p>
    <p>
      <%= form.submit "Create Project",class: "btn btn-primary" %>
    </p>
  <% end %>
</section>

app/views/projects/show.html.erb
<%= render partial: "layouts/nav", locals: {category: Category.find(@project.category_id)}  %>
<div class="container">
  <% if current_user %>
    <%= link_to "Edit Project", edit_category_project_path, class: "btn btn-primary" %>
    <%= link_to "Delete Project", category_project_path,
      method: :delete,
      data: { confirm: 'Kill the fuck out of this project, Ayesha?' },
      class: "btn btn-primary" %>
    <%= link_to "Add Image", "/categories/#{@project.category_id}/projects/#{@project.id}/pics/new", class: "btn btn-primary" %>
  <% end %>
</div>
<section class="container m-t-3">
  <div class="row">
    <%= image_tag @project.main_image_path.url(:medium), class: "col-sm-6 img-fluid" %>
    <div class="project-description col-sm-6">
      <h1><%= @project.title.upcase %></h1>
      <h3><%= @project.sales_pitch %></h3>
      <p class="lead description"><%= @project.description %></p>
    </div>
  </div>
</section>
<section class="container m-t-3">
  <% @project.pics.each do |pic| %>
    <div class="col-sm-6 m-t-2 bw pic">
      <% if pic.showable || current_user %>
        <%= link_to image_tag(pic.pic_path.url(:large), alt: pic.title, class: "img-fluid" ), "/categories/#{@project.category_id}/projects/#{@project.id}/pics/#{pic.id}" %>
        <h3 class="category-title"><%= pic.title %></h3>
      <% else %>
        <%= image_tag(pic.pic_path.url(:large), alt: pic.title, class: "img-fluid" ) %>
        <h3 class="category-title"><%= pic.title %></h3>
      <% end %>
    </div>
  <% end %>
</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>